2018-12-02 10:07:23,774 ERROR: Exception on /trip/make_trip [POST] [in /home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/aleksey/Документы/project/app/trip/routes.py", line 17, in make_trip
    if form.no_driver.data == True:
AttributeError: 'MakeTripForm' object has no attribute 'no_driver'
2018-12-02 10:08:29,490 INFO: pop startup [in /home/aleksey/Документы/project/app/__init__.py:60
2018-12-02 10:08:41,317 ERROR: Exception on /trip/make_trip [POST] [in /home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/aleksey/Документы/project/app/trip/routes.py", line 17, in make_trip
    if form.no_driver.data == True:
AttributeError: 'MakeTripForm' object has no attribute 'no_driver'
2018-12-02 22:22:05,947 INFO: pop startup [in /home/aleksey/Документы/project/app/__init__.py:60
2018-12-02 22:28:47,698 ERROR: Exception on /trip/2 [GET] [in /home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aleksey/pythonvenv/flask-env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/aleksey/Документы/project/app/trip/routes.py", line 45, in trip
    Trip(passengers.append(current_user))
NameError: name 'passengers' is not defined
2018-12-03 18:16:19,712 INFO: pop startup [in /home/aleksey/Документы/project/app/__init__.py:60
2018-12-03 18:19:34,742 INFO: pop startup [in /home/aleksey/Документы/project/app/__init__.py:60
2018-12-03 18:45:16,621 INFO: pop startup [in /home/aleksey/Документы/project/app/__init__.py:60
2018-12-03 18:45:39,630 INFO: pop startup [in /home/aleksey/Документы/project/app/__init__.py:60
2018-12-03 18:46:05,633 INFO: pop startup [in /home/aleksey/Документы/project/app/__init__.py:60
